version: '3.9'

services:
  iq_bot:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /var/log/iqbot:/app/logs
    depends_on:
      - redis


  redis:
    image: redis:7.2.3
    restart: on-failure
    ports:
      - 6381:6381
    volumes:
      - /var/log/iqbot:/data

volumes:
    redis_data: